langauge: ruby
sudo: true
cache: bundler

branches:
  only: master

before_install:
  - rvm install 2.4.1

rvm:
  - 2.4.1

before_script:
  - chmod +x build.sh

script:
  - gem install bundler:1.15.4
  - ./build.sh

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

matrix:
  fast_finish: true
  include:
    - # GitHub Pages
      rvm: 2.4.1
      env: GH_PAGES=true
