langauge: ruby
sudo: true
cache: bundler

branches:
  only: master

before_install:
  - rvm install 2.3.3

rvm:
  - 2.3.3
  - jruby-1.7.25

before_script:
  - chmod +x build.sh

script:
  - ./build.sh

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

matrix:
  fast_finish: true
